// generated by lib/sync.js
// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run
    
import Clipping from './Clipping';
import Widget from './Widget';
import Homepage from './Homepage';
import Article from './Article';

export {
  Clipping, Widget, Homepage, Article
}