
// generated by lib/zesty/sync.js
// This is a required an autogenerated file from the Zesty.io NextJS integration
// This file is overwritten everytime the integration script is run, unless options.skip_config_overwrite is true

const { fetchZestyRedirects } = require('./lib/zesty/fetchRedirects');

module.exports = {
  trailingSlash: true,
  eslint: {
    ignoreDuringBuilds: true
  },
  async redirects() {
    return await fetchZestyRedirects()
  },
  env: {
      zesty: {
          instance_zuid: "8-cac2a4c1f3-6jx3t9", // zesty unique id of content instance
          stage: "https://qb1jbcfx-dev.webengine.zesty.io", // e.g. https://XYZ-dev.webengine.zesty.io
          production: "https://nextjsexamplewebsite.zesty.dev", // e.g. https://www.acme.com
          stage_password: "12345",
          src_dir: "", // where the next project has pages, components, etc folders
          options: {
            skip_config_overwrite: false, // for setups with custom config files, after initial setup of the env.zesty object, set to true
            model_ignore_list: [
              '6-xyz' // an array of models ZUIDs to ignore when creating component files in views/zesty
            ]
          }
      }
  }
}