/**
 * Zesty.io AutoGenerated Header Component
 * This file is used in [...slug.js] for example. It is not necceary and may be deleted or modified as needed.
 * 
 */

function Header() {
       
    return (
        <div><a href="/">Home</a></div>
    )
}

export default Header;
